CREATE DATABASE QLBH_64132763
GO

USE QLBH_64132763
GO

--Tạo bảng--
CREATE TABLE PRODUCT_CATEGORY 
(
	ID_PRODUCT_CATEGORY INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	NAME_PRODUCT_CATEGORY NVARCHAR(50),
	META_TITLE_PRODUCT_CATEGORY VARCHAR(250), --TÊN URL THÀNH KHÔNG DẤU--
	PARENTID_PRODUCT_CATEGORY INT, --ĐA TRỊ--
	DISPLAY_ORDER INT DEFAULT 0, --XUẤT HIỆN THEO THỨ TỰ--
	CREATED_DATE DATETIME DEFAULT GETDATE(),
	CREATED_BY NVARCHAR(50),
	MODIFIED_DATE DATETIME,
	MODIFIED_BY NVARCHAR(50),
	META_DESCRIPTIONS NVARCHAR(250),
	STATUS_PRODUCT_CATEGORY BIT DEFAULT 1,
	SHOW_ON_HOME BIT DEFAULT 0
)

CREATE TABLE PRODUCT
(
	ID_PRODUCT INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	CODE VARCHAR(10),
	NAME_PRODUCT NVARCHAR(250),
	DESCRIPTIONS_PRODUCT NVARCHAR(250),
	IMAGES NVARCHAR(250),	
	PRICE DECIMAL(18,0) DEFAULT 0 ,
	PRICE_SALE DECIMAL(18,0),
	QUANITY INT DEFAULT 0,
	DETAIL NVARCHAR(MAX),
	META_TITLE_PRODUCT VARCHAR(250), --TÊN URL THÀNH KHÔNG DẤU--
	CREATED_DATE DATETIME DEFAULT GETDATE(),
	CREATED_BY NVARCHAR(50),
	MODIFIED_DATE DATETIME,
	MODIFIED_BY NVARCHAR(50),
	META_DESCRIPTIONS NVARCHAR(250),
	STATUS_PRODUCT BIT DEFAULT 1,
	VIEW_COUNT INT DEFAULT 0,
	ID_CATEGORY INT,
	CONSTRAINT FK_PRODUCT_PRODUCT_CATEGORY FOREIGN KEY (ID_CATEGORY)
    REFERENCES PRODUCT_CATEGORY(ID_PRODUCT_CATEGORY)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)
ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_PRODUCT_CATEGORY FOREIGN KEY (ID_CATEGORY)
REFERENCES PRODUCT_CATEGORY(ID_PRODUCT_CATEGORY)
ON DELETE CASCADE
ON UPDATE CASCADE;

CREATE TABLE CATEGORY 
(
	ID_CATEGORY INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	NAME_CATEGORY NVARCHAR(50),
	META_TITLE_CATEGORY VARCHAR(250), --TÊN URL THÀNH KHÔNG DẤU--
	PARENTID_CATEGORY INT, --ĐA TRỊ--
	DISPLAY_ORDER INT DEFAULT 0, --XUẤT HIỆN THEO THỨ TỰ--
	CREATED_DATE DATETIME DEFAULT GETDATE(),
	CREATED_BY NVARCHAR(50),
	MODIFIED_DATE DATETIME,
	MODIFIED_BY NVARCHAR(50),
	META_DESCRIPTIONS NVARCHAR(250),
	STATUS_CATEGORY BIT DEFAULT 1,
	SHOW_ON_HOME BIT DEFAULT 0
)

CREATE TABLE ADVERTISEMENT
(
	ID_ADVERTISEMENT INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	NAME_ADVERTISEMENT NVARCHAR(250),
	DESCRIPTIONS_ADVERTISEMENT NVARCHAR(250),
	IMAGES NVARCHAR(250),	
	DETAIL NVARCHAR(MAX),
	META_TITLE_PRODUCT VARCHAR(250), --TÊN URL THÀNH KHÔNG DẤU--
	CREATED_DATE DATETIME DEFAULT GETDATE(),
	CREATED_BY NVARCHAR(50),
	MODIFIED_DATE DATETIME,
	MODIFIED_BY NVARCHAR(50),
	META_DESCRIPTIONS NVARCHAR(250),
	STATUS_ADVERTISEMENT BIT DEFAULT 1,
	VIEW_COUNT INT DEFAULT 0,
	ID_CATEGORY INT,
	TAG NVARCHAR(500)
	CONSTRAINT FK_ADVERTISEMENT_CATEGORY FOREIGN KEY (ID_CATEGORY)
    REFERENCES CATEGORY(ID_CATEGORY)
	ON DELETE CASCADE
	ON UPDATE CASCADE

)


CREATE TABLE TAG
(
	ID_TAG VARCHAR(50) NOT NULL PRIMARY KEY,
	NAME_TAGE NVARCHAR(50)
)

CREATE TABLE ADVERTISEMENT_TAG
(
	ID_TAG VARCHAR(50),
	ID_ADVERTISEMENT INT,
	CONSTRAINT PK_ADVERTISEMENT_TAG PRIMARY KEY (ID_TAG, ID_ADVERTISEMENT),
	CONSTRAINT FK_ADVERTISEMENT_TAG_ADVERTISEMENT FOREIGN KEY (ID_ADVERTISEMENT)
    REFERENCES ADVERTISEMENT(ID_ADVERTISEMENT)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
    CONSTRAINT FK_ADVERTISEMENT_TAG_TAG FOREIGN KEY (ID_TAG)
    REFERENCES TAG(ID_TAG)
)

CREATE TABLE MENU_TYPE
(
	ID_TYPE VARCHAR(50) NOT NULL PRIMARY KEY,
	NAME_TYPE NVARCHAR(50)
)

CREATE TABLE MENU
(
	ID_MENU INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	CONTENT NVARCHAR(50),
	LINK NVARCHAR(250),
	DISPLAY_ORDER INT DEFAULT 0, --XUẤT HIỆN THEO THỨ TỰ--
	TARGET_MENU NVARCHAR(50),
	STATUS_SLIDE BIT DEFAULT 1,
	ID_TYPE VARCHAR(50)
	CONSTRAINT FK_MENU_MENU_TYPE FOREIGN KEY (ID_TYPE)
    REFERENCES MENU_TYPE(ID_TYPE),
)


CREATE TABLE USER_ROLE
(
	ID_USER INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	NAME_USER VARCHAR(50),
	PASSWORD_USER VARCHAR(128),
	LAST_NAME NVARCHAR(50),
	FIRST_NAME NVARCHAR(50),
	ADDRESS_CUSTOMER NVARCHAR(50),
	EMAIL NVARCHAR(50),
	PHONE NVARCHAR(50),
	CREATED_DATE DATETIME DEFAULT GETDATE(),
	CREATED_BY NVARCHAR(50),
	MODIFIED_DATE DATETIME,
	MODIFIED_BY NVARCHAR(50),
	STATUS_SLIDE BIT DEFAULT 1

)

CREATE TABLE CART
(
	ID_CART INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	CREATED_DATE DATETIME DEFAULT GETDATE(),
	SHIP_NAME NVARCHAR(50), 
	SHIP_MOBILE VARCHAR(50),
	SHIP_ADDRESS NVARCHAR(50),
	SHIP_EMAIL NVARCHAR(50),
	ID_USER INT,
	STATUS_CART INT,
	CONSTRAINT FK_CART_USER FOREIGN KEY (ID_USER)
    REFERENCES USER_ROLE(ID_USER),
)

CREATE TABLE CART_DETAIL
(
	ID_PRODUCT INT,
	ID_CART INT,
	QUANTITY INT,
	PRICE DECIMAL(18,0)
	CONSTRAINT PK_PRODUCT_CART PRIMARY KEY (ID_PRODUCT, ID_CART),
	CONSTRAINT FK_CART_DETAIL_USER FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT),
	CONSTRAINT FK_CART_DETAIL_CART FOREIGN KEY (ID_CART) REFERENCES CART(ID_CART),
)

ALTER TABLE PRODUCT
ALTER COLUMN META_DESCRIPTIONS NVARCHAR(500)

INSERT INTO USER_ROLE (NAME_USER, PASSWORD_USER, LAST_NAME, FIRST_NAME, ADDRESS_CUSTOMER, EMAIL, PHONE, CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY, STATUS_SLIDE)
VALUES 
('adm', '123', 'Doe', 'John', '123 Example Street', 'john.doe@example.com', '123-456-7890', GETDATE(), 'admin', NULL, NULL, 0);

INSERT INTO USER_ROLE (NAME_USER, PASSWORD_USER, LAST_NAME, FIRST_NAME, ADDRESS_CUSTOMER, EMAIL, PHONE, CREATED_DATE, CREATED_BY, MODIFIED_DATE, MODIFIED_BY, STATUS_SLIDE)
VALUES 
('admin', 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', 'Doe', 'John', '123 Example Street', 'john.doe@example.com', '123-456-7890', GETDATE(), 'admin', NULL, NULL, 1);

-- Insert Accessory Category
INSERT INTO PRODUCT_CATEGORY 
(NAME_PRODUCT_CATEGORY, META_TITLE_PRODUCT_CATEGORY, PARENTID_PRODUCT_CATEGORY, DISPLAY_ORDER, CREATED_DATE, CREATED_BY, META_DESCRIPTIONS, STATUS_PRODUCT_CATEGORY, SHOW_ON_HOME)
VALUES
('Accessory', 'accessory', NULL, 1, GETDATE(), 'Admin', 'Category for accessories', 1, 1);

-- Insert Top Category
INSERT INTO PRODUCT_CATEGORY 
(NAME_PRODUCT_CATEGORY, META_TITLE_PRODUCT_CATEGORY, PARENTID_PRODUCT_CATEGORY, DISPLAY_ORDER, CREATED_DATE, CREATED_BY, META_DESCRIPTIONS, STATUS_PRODUCT_CATEGORY, SHOW_ON_HOME)
VALUES
('Top', 'top', NULL, 2, GETDATE(), 'Admin', 'Category for tops', 1, 1);

-- Insert Bottom Category
INSERT INTO PRODUCT_CATEGORY 
(NAME_PRODUCT_CATEGORY, META_TITLE_PRODUCT_CATEGORY, PARENTID_PRODUCT_CATEGORY, DISPLAY_ORDER, CREATED_DATE, CREATED_BY, META_DESCRIPTIONS, STATUS_PRODUCT_CATEGORY, SHOW_ON_HOME)
VALUES
('Bottom', 'bottom', NULL, 3, GETDATE(), 'Admin', 'Category for bottoms', 1, 1);

-- Accessory
INSERT INTO PRODUCT (CODE, NAME_PRODUCT, DESCRIPTIONS_PRODUCT, IMAGES, PRICE, PRICE_SALE, QUANITY, DETAIL, META_TITLE_PRODUCT, CREATED_DATE, CREATED_BY, META_DESCRIPTIONS, STATUS_PRODUCT, VIEW_COUNT, ID_CATEGORY)
VALUES
('ACC001', 'Silk Scarf', 'A fashionable silk scarf for women.', 'product_1.jpg', 200000, 150000, 50, 'Soft material, elegant design.', 'silk-scarf', GETDATE(), 'Admin', 'Stylish silk scarf for women', 1, 20, 1),
('ACC002', 'Silver Bracelet', '925 silver bracelet with a modern look.', 'product_2.jpg', 300000, 250000, 30, 'Modern and trendy design.', 'silver-bracelet', GETDATE(), 'Admin', 'Silver bracelet for women', 1, 15, 1),
('ACC003', 'Mini Handbag', 'Compact and convenient mini handbag.', 'product_3.jpg', 500000, 450000, 20, 'High-quality mini handbag.', 'mini-handbag', GETDATE(), 'Admin', 'Mini handbag for women', 1, 25, 1);

-- Top
INSERT INTO PRODUCT (CODE, NAME_PRODUCT, DESCRIPTIONS_PRODUCT, IMAGES, PRICE, PRICE_SALE, QUANITY, DETAIL, META_TITLE_PRODUCT, CREATED_DATE, CREATED_BY, META_DESCRIPTIONS, STATUS_PRODUCT, VIEW_COUNT, ID_CATEGORY)
VALUES
('TOP001', 'Basic White T-Shirt', 'Basic white T-shirt for women.', 'product_4.jpg', 200000, 180000, 50, 'Comfortable cotton material.', 'basic-white-tshirt', GETDATE(), 'Admin', 'Basic white T-shirt for women', 1, 25, 2),
('TOP002', 'Chiffon Blouse', 'Elegant chiffon blouse for office wear.', 'product_5.jpg', 350000, 320000, 30, 'Soft and suitable for work.', 'chiffon-blouse', GETDATE(), 'Admin', 'Chiffon blouse for women', 1, 15, 2),
('TOP003', 'Knitted Sweater', 'Stylish knitted sweater.', 'product_6.jpg', 400000, 380000, 20, 'Perfect for cold weather.', 'knitted-sweater', GETDATE(), 'Admin', 'Knitted sweater for women', 1, 30, 2);

-- Bottom
INSERT INTO PRODUCT (CODE, NAME_PRODUCT, DESCRIPTIONS_PRODUCT, IMAGES, PRICE, PRICE_SALE, QUANITY, DETAIL, META_TITLE_PRODUCT, CREATED_DATE, CREATED_BY, META_DESCRIPTIONS, STATUS_PRODUCT, VIEW_COUNT, ID_CATEGORY)
VALUES
('BOT001', 'Skinny Jeans', 'Slim-fit jeans for women.', 'product_7.jpg', 400000, 370000, 40, 'Stretchable and easy to style.', 'skinny-jeans', GETDATE(), 'Admin', 'Skinny jeans for women', 1, 25, 3),
('BOT002', 'Shorts', 'Comfortable cotton shorts.', 'product_8.jpg', 300000, 270000, 50, 'Lightweight and breathable.', 'shorts', GETDATE(), 'Admin', 'Casual shorts for women', 1, 30, 3),
('BOT003', 'Flared Skirt', 'Stylish flared skirt.', 'product_9.jpg', 350000, 320000, 35, 'Chic and versatile design.', 'flared-skirt', GETDATE(), 'Admin', 'Flared skirt for women', 1, 20, 3),
('BOT004', 'Office Pants', 'Elegant office pants for work.', 'product_10.jpg', 500000, 450000, 25, 'Perfect for formal settings.', 'office-pants', GETDATE(), 'Admin', 'Office pants for women', 1, 15, 3);
